name: CI de Spring Boot con Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Distribución del JDK (ej. 'adopt', 'microsoft', etc.)
          java-version: '17'     # ¡Importante! Cambia esto a la versión de Java que usa tu proyecto
          cache: 'maven'         # Configura el cache para las dependencias de Maven

      - name: Construir con Maven y ejecutar pruebas
        run: mvn -B package --file pom.xml
        # Este comando compilará tu código y lo empaquetará.
        # Si no hay pruebas, la fase de pruebas simplemente se omitirá.
        # Cuando añadas pruebas en el futuro, este mismo comando las ejecutará automáticamente.